# Generated by Django 2.2.6 on 2022-02-08 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20220208_2358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amount',
            old_name='quantity',
            new_name='amount',
        ),
    ]
